<?xml version="1.0"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:fo="http://www.w3.org/1999/XSL/Format"
    xmlns:axf="http://www.antennahouse.com/names/XSL/Extensions"
    version="2.0">
 	<xsl:import href="ast-basic-settings.xsl" />
 	<xsl:import href="ast-commons-attr.xsl" />
 	<xsl:import href="ast-front-matter-attr.xsl" />
 	<xsl:import href="ast-hi-domain-attr.xsl" />
 	<xsl:import href="ast-layout-masters-attr.xsl" />
 	<xsl:import href="ast-links-attr.xsl" />
 	<xsl:import href="ast-lists-attr.xsl" />
 	<xsl:import href="ast-static-content-attr.xsl" />
 	<xsl:import href="ast-sw-domain-attr.xsl" />
 	<xsl:import href="ast-tables-attr.xsl" />
 	<xsl:import href="ast-task-elements-attr.xsl" />
 	<xsl:import href="ast-toc-attr.xsl" />
 	<xsl:import href="ast-topic-attr.xsl" />
</xsl:stylesheet>
